### ISSUE TITLE
Don't lock JSCS version

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/grunt-jscs#107]
The package.json should specify >= version for JSCS so that as new versions come out, people can try to use them without requiring this package to be bumped.

**Comment by markelog** [comment]
See https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#user-content-versioning--semver

**Comment by TheSavior** [comment]
I don't see how the semver rules for JSCS should effect grunt-jscs. Grunt-JSCS could just specify JSCS as a peer dependency and let the user manage the version.

**Comment by markelog** [comment]
> I don't see how the semver rules for JSCS should effect grunt-jscs

plugin follows the same semver strategy.

> Grunt-JSCS could just specify JSCS as a peer dependency and let the user manage the version.

I think that would be a simplifcation for the plugin writer but not for the user
