### ISSUE TITLE
requireVarDeclFirst error when comment in function expression

### ISSUE THREAD

**Issue by galvarez421** [jscs-dev/grunt-jscs#108]
Rule: requireVarDeclFirst: true
Code that will make grunt-jscs exhibit the issue:

    var test = function() {
      var color = "grey";
      // This is a comment
    };
    var test2 = "string";

The task will report an error for the line with the second assignment, but if I remove the comment in the function expression, the error goes away.

Using grunt-jscs version 2.5.0
Operating system: Windows 7 64-bit

**Comment by gustavohenke** [comment]
You should report this to [JSCS core](https://github.com/jscs-dev/node-jscs) instead.

**Comment by galvarez421** [comment]
Will do! I wasn't actually sure if it is an issue with the core or the Grunt task specifically, so I figured I'd start with the narrowest option.

**Comment by gustavohenke** [comment]
OK, if you can reproduce this with JSCS itself, let me know, so we can close this one!

If you don't, then it's definitely a issue with the Grunt plugin :confused:

**Comment by galvarez421** [comment]
Yes, I am able to reproduce it in JSCS itself! Thanks for the prompt replies.
