### ISSUE TITLE
config property not defaulting to true if verbose property included

### ISSUE THREAD

**Issue by galvarez421** [jscs-dev/grunt-jscs#110]
grunt: 0.4.5
grunt-jscs: 2.6.0

.jscsrc content: any

In "jscs.options" object, if config property is omitted (and should therefore default to true), errors will be reported according to the .jscsrc file (as if config === true) but only if the verbose property is not included. In other words, if config property is omitted and verbose property is included (verbose === true or verbose === false), errors will not be reported according to the .jscsrc file.

**Comment by markelog** [comment]
Yes, that happens for any jscs option, you think we should merge those options?

**Comment by galvarez421** [comment]
Sorry, but I still don't fully understand the current behavior. What is the config option in the grunt-jscs plugin being set to when verbose is explicitly set to a value? And why is an explicit verbose property affecting the value of the config property?

**Comment by markelog** [comment]
We probably not gonna fix this at this point
