### ISSUE TITLE
Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by thedigitalman** [jscs-dev/grunt-jscs#112]
After running npm-install and flatten-packages on my node_modules directory, I get the following error message when running any task that uses jscs:

"Error: Cannot find module 'lodash/lang/isFunction"

I have tried removing the node_modules folder, clearing npm cache, and reinstalling.  But, that has not worked for me.

Any advice would be very welcome.

Thanks.

-----

OS: Windows 7

`  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-accessibility": "^3.5.1",
    "grunt-asset-cachebuster": "^0.4.0",
    "grunt-concurrent": "^2.1.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-jshint": "^0.12.0",
    "grunt-contrib-sass": "^0.9.2",
    "grunt-contrib-uglify": "^0.11.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-cssnano": "^2.0.1",
    "grunt-html": "^6.0.0",
    "grunt-jscs": "^2.7.0",
    "grunt-postcss": "^0.7.1",
    "postcss-discard-comments": "^2.0.3"
  }`

**Comment by markelog** [comment]
Hm, that's really weird, we don't even use that module directly, but we need to update lodash to 4 version anyway, hopefully this error will go away after that

**Comment by thedigitalman** [comment]
Running this is the same directory solves the problem:

`npm i --save lodash`

**Comment by thedigitalman** [comment]
This solution is not working for me on a separate PC, so it's still an issue.

**Comment by markelog** [comment]
Don't know what to tell you, honestly, we don't require such module anywhere in the code base, nor the jscs itself
