### ISSUE TITLE
Use of "force" option should not disable reporter

### ISSUE THREAD

**Issue by marob** [jscs-dev/grunt-jscs#113]
If the "force" option is enabled (true), the reporter is disabled: no detail of jscs violations are written in the console/file.

My use case is to generate a jscs report (in checkstyle or junit format) in continuous integration but not to fail the build. If I set "force" to true, my report is (nearly) empty and do not list jscs violations. If I set "force" to false, my report is complete, but the build fails.

**Comment by markelog** [comment]
Did the jscs fix all the errors? Or there some errors left, but they are not outputted?

**Comment by marob** [comment]
Nothing has been fixed as I have not set the boolean "fix" to true.

**Comment by markelog** [comment]
I'm trying to clarify this bit - 

> If the "force" option is enabled (true), the reporter is disabled: no detail of jscs violations are written in the console/file.

**Comment by marob** [comment]
Launching with "force: false" outputs some jscs violations (count of violations + detail of violations) in the console.
If we launch again with "force: true", the console output still has jscs violation count, but without details.

The problem is, if you use some reporterOutput (say Checkstyle or Junit), the content of the file is:

- empty with "force: true"
- filled with jscs violations with "force: false"

So the build can either not fail, either output the jscs violations in a file. But it can't do both.

**Comment by markelog** [comment]
We probably not gonna fix this at this point
