### ISSUE TITLE
Disallow spaces before new line

### ISSUE THREAD

**Issue by Lipata** [jscs-dev/grunt-jscs#115]
I'm searching for an option to disallow spaces, before a new line. Searching [here](http://jscs.info/rules) it seems I'm missing it or it doesn't have such?

I want to get error, when those 4 points, after the closing bracket, exist :
![image](https://cloud.githubusercontent.com/assets/2621802/12851776/693272e6-cc34-11e5-9622-989a06307f3d.png)

Thank you very much for the help.
Regards,
Nikolay

**Comment by gustavohenke** [comment]
You're looking at the [`disallowTrailingWhitespace` rule](http://jscs.info/rule/disallowTrailingWhitespace)

**Comment by Lipata** [comment]
Thank you Gustavo.
