### ISSUE TITLE
Q: Supply config with url to jscsrc

### ISSUE THREAD

**Issue by Mutmatt** [jscs-dev/grunt-jscs#119]
Is it possible to supply the config with a url instead of a file on the local filesystem?

**Comment by gustavohenke** [comment]
[This is one is handled by JSCS itself](https://github.com/jscs-dev/grunt-jscs/blob/aa8ec81/tasks/lib/jscs.js#L120).

@markelog, anything that you could anticipate us? I'm kinda out of JSCS world

**Comment by markelog** [comment]
No :), i'd say it would be really weird feature.

**Comment by Mutmatt** [comment]
What do you mean by "weird?" Is there some reason why an online repo hosting a file seems weird?  We do things like this for resources like jQuery, angular, phantomjs

**Comment by gustavohenke** [comment]
I think his opinion on this is because you would be configuring JSCS on top of an external resource.
This means that your builds could start failing even though none of your dependencies have changed.
