### ISSUE TITLE
"disallowMultipleVarDecl": {"allExcept": ["require"]} is ignored by grunt-jscs

### ISSUE THREAD

**Issue by zoejobson** [jscs-dev/grunt-jscs#120]
the option "disallowMultipleVarDecl": {"allExcept": ["require"]}, is part of jscs 2.0 and above, but is ignored when using jcsc via grunt.

**Comment by markelog** [comment]
Very much doubt that, but if you could provide a test repo to review, i can re-open, sorry it took so long to review this btw
