### ISSUE TITLE
Convert from using jscs(depricated) in favor of ESLint

### ISSUE THREAD

**Issue by PseudoNinja** [jscs-dev/grunt-jscs#137]
node-jscs has hit EOL and is no longer being developed en lieu of team joing ESLint.

jscs is full of security vulnerabilities that need to be patched but being a sunset product it will never be updated. Teh grunt jscs library is actively being utilized by jquery-ui which is consumed by thousands of products.

**Comment by gustavohenke** [comment]
Huh, this has been discontinued as well... And it is exactly a library to provide an entry point into JSCS from Grunt 🤔

If it's a problem for jquery-ui, then it should be dropped there?

I bet that there already is a grunt-eslint library somewhere that will do the job better?

**Comment by PseudoNinja** [comment]
@gustavohenke if that's the case then I recommend archiving this repository and dropping a note in the ReadME
