### ISSUE TITLE
Verbose flag

### ISSUE THREAD

**Issue by markelog** [jscs-dev/grunt-jscs#72]
So you could define it through the grunt task?

**Comment by gustavohenke** [comment]
A must (Y)

**Comment by aj-dev** [comment]
+1

**Comment by jzaefferer** [comment]
`verbose` isn't the only flag that `jscs` has that isn't available through this wrapper, though its the one I've missed as well.

**Comment by markelog** [comment]
Fixed via https://github.com/jscs-dev/node-jscs/commit/db09ceceb5fd3a05a9dd70c2388a12dbf8b7cdb2, pulled in https://github.com/jscs-dev/grunt-jscs/commit/4d7cf39f5c5bc37481e47ef24fbc1b91549b66b8

**Comment by jzaefferer** [comment]
Could you document how to use the verbose option here? Based on the commit references I can't tell.

**Comment by markelog** [comment]
@jzaefferer see docs in http://jscs.info/overview.html#verbose

**Comment by jzaefferer** [comment]
Right, but where do I specify that when using this grunt plugin? As a property in the `options`?

**Comment by markelog** [comment]
Hm, weird that confuses you, you can do this either in `options` just like any other jscs option or in jscs config

**Comment by markelog** [comment]
@jzaefferer if something is unclear, please let me know, perhaps we could add more clear info in the docs

**Comment by jzaefferer** [comment]
Adding the `verbose` flag to one of the usage examples would help a lot. With a comment like
```
// When you don't know what rule is causing a warning, set this
```

**Comment by markelog** [comment]
Well, grunt-jscs is just a proxy to the jscs, so any rule or option like `verbose` that defined in the jscs config will be used.

Is that not clear?

**Comment by markelog** [comment]
So basically, we don't actually have `verbose` option, jscs does

**Comment by jzaefferer** [comment]
When I found this issue back in March, my workflow was roughly this: I ran jscs, a bunch of rules were generating errors. I wanted to disable those rules, but couldn't figure out what their config keys are. I figured that it would be helpful to have the error also output the key of the rule and eventually found the issue about the verbose flag. I then tried to use that flag with this plugin, but it wouldn't work.

Now imagine the same situation. Someone else runs into the same issue, checks the grunt plugin for options and finds... nothing. Might then check jscs itself and find the verbose flag, but its still not obvious that you can pass options through to jscs. Adding it to one of the examples here would make it easier to discover, while barely adding two lines.

That is all. Not a big deal, but as documentation goes, details matter.

**Comment by markelog** [comment]
I guess this is same issue as in https://github.com/jscs-dev/grunt-jscs/issues/88, i added couple more examples in grunt-jscs docs. Plus in couple weeks jscs.info should be updated too, i hope it will help to the described use-cases.

**Comment by SaurabhJha** [comment]
@markelog Thanks for helping everyone. I downloaded the latest grunt-scs (1.8.0) which points to jscs@1.13.1. I am still not able to activate verbose: true. Here is my configuration

module.exports = {
    src: 'src/**/*.js',
    options: {
        preset: "crockford",
        verbose: true
    }
}

**Comment by markelog** [comment]
@SaurabhJha i'm afraid we need more info then that, if you could point on your repository or re-create it as example in the github would perfect.
