### ISSUE TITLE
Default configuration file

### ISSUE THREAD

**Issue by michaelBenin** [jscs-dev/grunt-jscs#73]
Would be nice to have a default configuration file defined. 

Running "jscs:files" (jscs) task
Fatal error: Neither config file nor grunt options were defined

**Comment by gustavohenke** [comment]
You must have a `.jscsrc` or `.jscs.json` file in your project.
See https://github.com/jscs-dev/grunt-jscs#config for reference.

**Comment by markelog** [comment]
> Would be nice to have a default configuration file defined.

Yeah, jscs doesn't have any pre-defined options.
