### ISSUE TITLE
Update the node-jscs version

### ISSUE THREAD

**Issue by yaycmyk** [jscs-dev/grunt-jscs#75]
Could you loosen this up a bit? Perhaps switch to caret notation so we can get updates more fluidly from the main project?

**Comment by gustavohenke** [comment]
I tried to change this, but @markelog is against :cry:

**Comment by markelog** [comment]
Oh, well, i have good reason, check it out - http://jscs.info/overview.html#versioning-semver.

If we do this, users will get unstable releases i.e. they might get unexpected failures.

For example, grunt-jscs, releases when travis detects tag commit, the same tool run the code-style check. It will not release if there would be any failures.

Now if you would use caret, you might get a failure even if you just changed `version` field in `package.json` and nothing else. In this situation, project wouldn't be released.

There is a lot of use-cases where that wouldn't be desirable, i think most of us wouldn't want to see solid code-base to fail for no apparent reason, like airbnb preset changed one of their rules on the opposite one, jscs released this change in minor release. If you using this preset, you would see thousands of errors, when you might not change a thing. Errors with the code-style nonetheless not with logic. Why you would want that?

Whereas you could always loosen your `grunt-jscs` dependency, you could always use caret in your project.

I guess, this would be more annoying if we would change it.

**Comment by gustavohenke** [comment]
> Whereas you could always loosen your grunt-jscs dependency, you could always use caret in your project.

Correct.

Anyway, grunt-jscs is a project by the JSCS team, so updates occur quickly.
If it was developed by a 3rd party, that would be a problem, because the 3rd party could be away or without interest.

Thank you, @markelog :+1:

**Comment by yaycmyk** [comment]
@markelog Using caret notation wouldn't cause catastrophic issues, per your comment on semver. If JSCS was to make a major change, they would have to increment the major version and `^` restricts the version used to the highest available within the same major version.
