### ISSUE TITLE
Clarification over block expression and anonymous function spaces

### ISSUE THREAD

**Issue by gunnx** [jscs-dev/grunt-jscs#77]
If you have this code:

```
var x = (function(){
  // do stuff
})();
```

The rule "requireSpaceBeforeBlockStatements": true kicks in which conflicts with 
```
"disallowSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
}
```

Is this expected behaviour? It would be useful to get feedback on usage of rules that are conflicting.

I found the spacing rules around function declaration/expressions named/anonymous a bit confusing. 

Thanks

**Comment by gustavohenke** [comment]
I agree, that's strange and may be a bug, but you should report this to [JSCS core](/jscs-dev/node-jscs) instead.
@markelog, @mikesherov and the other guys will make the best to help you.
