### ISSUE TITLE
Out of sync with node-jscs

### ISSUE THREAD

**Issue by n8io** [jscs-dev/grunt-jscs#78]
I am getting this when trying to run with a jscs@1.11.3 compatible config.

```Warning: Unsupported rules: disallowOperatorBeforeLineBreak, disallowPaddingNewlinesBeforeKeywords, requirePaddingNewlinesBeforeKeywords, requireSpaceBetweenArguments, requireSpacesInForStatement Use --force to continue.```

Shouldn't new (read unsupported) rules be ignored rather than explode?

**Comment by gustavohenke** [comment]
> Shouldn't new (read unsupported) rules be ignored rather than explode?

That's a choice from JSCS itself.

But, [it's very common to miss the JSCS version](https://github.com/jscs-dev/node-jscs/issues?q=is%3Aissue+Unsupported+rules+is%3Aclosed). Make sure you're using grunt-jscs 1.4.0+.

**Comment by gustavohenke** [comment]
It's been a while without any further comments, so I'm closing this issue.
Feel free to get back to discussion if you want.
