### ISSUE TITLE
esprima customization

### ISSUE THREAD

**Issue by gyzerok** [jscs-dev/grunt-jscs#79]
How do I customize esprime?

Missed in docs.

**Comment by gustavohenke** [comment]
The Grunt task will forward every option to JSCS, [except a few specific ones](https://github.com/jscs-dev/grunt-jscs/blob/8e17966c67239a82700713a1dd7225313ca47e5f/tasks/lib/jscs.js#L12).

That being said, if JSCS supports it via config file, it should be supported by grunt-jscs. But this isn't documented [here](http://jscs.info/overview.html#options), so I'm unsure if you are supposed to customize Esprima [only via CLI](http://jscs.info/overview.html#-esprima-) or what.

@markelog thoughts?

**Comment by markelog** [comment]
We don't test this specific option, but yeah, esprima should be <a href="http://jscs.info/overview.html#esprimaoptions">customizeble</a>.

**Comment by markelog** [comment]
Seems we good here
