### ISSUE TITLE
Bump JSCS to 1.12.0

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/grunt-jscs#81]

**Comment by markelog** [comment]
That was fast :-), fixed via https://github.com/jscs-dev/grunt-jscs/commit/bb98fca2c6184e4cc9963cdab7e4f2613701a38f

**Comment by TheSavior** [comment]
Thanks. :)

**Comment by TheSavior** [comment]
Did this get published to npm as well? :D

**Comment by markelog** [comment]
It publishes automatically when CI detects the new tag, commit is in the travis queue right now

**Comment by TheSavior** [comment]
Oh, that's pretty neat. I didn't know you could do that. haha
