### ISSUE TITLE
Support "auto-fixing" and "auto-configure" options

### ISSUE THREAD

**Issue by markelog** [jscs-dev/grunt-jscs#82]
Not totally sure about them, since they might be out of scope of this plugin, but, why not?

**Comment by yaycmyk** [comment]
:+1:

**Comment by LostSenSS** [comment]
:+1:

**Comment by jlnslv** [comment]
+1

**Comment by andrewaustin** [comment]
:+1:

**Comment by Rleahy22** [comment]
+1

**Comment by varemenos** [comment]
:+1:

**Comment by markelog** [comment]
Yeah, yeah, i get it you guys, will work on it as soon i have time, meanwhile, if someone wants to send us PR he/she would be a real hero :-)

**Comment by jared-christensen** [comment]
:+1:

**Comment by oric01** [comment]
:+1:

**Comment by qikkeronline** [comment]
:+1: (awesome grunt plugin btw)

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by peter-razorfish** [comment]
+1

**Comment by gustavohenke** [comment]
Maybe someone will want to answer this when this is implemented: 
http://stackoverflow.com/questions/29640872/how-can-i-get-jscs-to-use-the-fix-option-from-grunt

**Comment by markelog** [comment]
`auto-configure` i guess is redundant, but auto-fixing is in, thanks to @spalger, released in version 1.8
