### ISSUE TITLE
Document how to use `esnext`

### ISSUE THREAD

**Issue by scottgonzalez** [jscs-dev/grunt-jscs#88]
Ref #62.

**Comment by markelog** [comment]
Well, `esnext` just like any other jscs option or rules could be defined in the `options` or in jscs config - http://jscs.info/overview.html#esnext

**Comment by markelog** [comment]
So, like
```js
{
  "preset": "jquery",
  "esnext": true
}
```

Isn't that clear?

**Comment by scottgonzalez** [comment]
I honestly did not realize that you could pass `esnext` as an option in jscs, I thought you had to pass it as a command line argument.

**Comment by markelog** [comment]
Could propose a solution to make it more clear?

**Comment by scottgonzalez** [comment]
Reorganize the whole Overview page. Move the Installation, Versioning & Semver, and Friendly Packages sections to an Install page. Start with an actual overview: Explain the use of `.jscsrc`, along with a link to the Rules page. Then show the list of presets and link to the Friendly Packages section of the Install page. Then Error Suppression and CLI. I'd get rid of the Disabling a Rule subsection since as far as I can tell, it only applies to the use of presets, and equivalent text already exists in that section. In the CLI section, add a note for any option that can also be used as a rule.

For the rules, add categorization (disallow vs. require, whitespace, naming, etc.) and "see also" links (requireSpacesInsideBrackets, requireSpacesInsideArrayBrackets, requireSpacesInsideObjectBrackets, and associated disallow rules as an example). Add permalinks (the hashes exist, the links don't). Perhaps make it possible to collapse everything; right now, getting just a list of rules for a quick overview requires using the console.

**Comment by markelog** [comment]
Thank you Scott! We will try to incorporate your suggestions into the new site
