### ISSUE TITLE
Support for rule disabling via inline comments

### ISSUE THREAD

**Issue by boyomarinov** [jscs-dev/grunt-jscs#89]
`JSCS` has the possibility to disable either all rules or specific ones for a given code section (http://jscs.info/overview.html#inline-comments).
 + // jscs:disable
 + // jscs:disable [rule-name]

However using `grunt-jscs` to validate source files seems to ignore those comments.

**Comment by markelog** [comment]
Those comments are supported, could you provide a test-case?

**Comment by boyomarinov** [comment]
Ah man, sorry for the trouble, the comments are indeed working in an isolated example (https://github.com/boyomarinov/grunt-jscs-showcase.git). At the office I have much more complicated grunt config, so the problem might be somewhere else. Closing the issue, cheers.
