### ISSUE TITLE
Fatal error: Neither config file nor grunt options were defined

### ISSUE THREAD

**Issue by OliverJAsh** [jscs-dev/grunt-jscs#91]
When I don't define an `options` object, I get the following error:

```
Fatal error: Neither config file nor grunt options were defined
```

I thought the default config was set to `true`? I do have a `.jscsrc` file.

**Comment by markelog** [comment]
It is, could you show me the repo?

**Comment by markelog** [comment]
Okay, closing for now, if you still facing this issue, please ping us up
