### ISSUE TITLE
Merge custom options with jscsrc

### ISSUE THREAD

**Issue by OliverJAsh** [jscs-dev/grunt-jscs#92]
If I don't specify a config, JSCS will read my `.jscsrc` file. If I specify other options, such as `esnext`, grunt-jscs will only use these options—it will not attempt to merge them with my `.jscsrc` file.

Could we merge with the `.jscsrc` file?

**Comment by markelog** [comment]
```js
jscs: {
    src: "path/to/files/*.js",
    options: {
        config: true,
        requireCurlyBraces: [ "if" ]
    }
}
```

This doesn't work for you?

**Comment by OliverJAsh** [comment]
It doesn't work when `config: '.jscsrc'`.

**Comment by markelog** [comment]
Hm, i added test that should check exactly this use-case - https://github.com/jscs-dev/grunt-jscs/commit/49936c602fd0ca77e1978be8680ba1b4073ebe4b

Do not see any errors, would you mind providing a pr with test or repo with this reproducible issue?

**Comment by markelog** [comment]
Did you resolve the issue?
