### ISSUE TITLE
Update for JSCS 2.2.x

### ISSUE THREAD

**Issue by paulschreiber** [jscs-dev/grunt-jscs#96]
Please update the dependency to 2.2.x.

**Comment by harm-less** [comment]
+1

**Comment by di5abled** [comment]
+1

**Comment by fluky** [comment]
+1 but let's make it 2.3.x

2.1 has a lot of issues.

**Comment by tclindner** [comment]
+1

**Comment by dsine-de** [comment]
Yes please

**Comment by TheHalcyonSavant** [comment]
+1 for 2.3.x

**Comment by markelog** [comment]
ooh, will do that tomorrow

**Comment by dimafeldman** [comment]
I'd even go a bit further and update to 2.3.5 :)

**Comment by markelog** [comment]
Actually, we will update to `2.4`, which will be released tomorrow - https://github.com/jscs-dev/grunt-jscs/pull/101
